### ISSUE TITLE
Tokens for address fields bleed into all entity fields

### ISSUE THREAD

**Issue by sentaidigital** [backdrop-contrib/addressfield#13]
When browsing available tokens for a content type, such as when editing the URL pattern, the addressfield subtokens apply to all the fields.  For example, in the attached screenshot, the image field has all of the tokens for an addressfield. 

Even if no addressfield fields exist, the tokens are applied to all fields.

**Comment by sentaidigital** [comment]
![screen shot 2016-03-21 at 11 18 21 pm](https://cloud.githubusercontent.com/assets/481531/13941388/9fa1e63e-efbd-11e5-80a0-38922ef5c03f.png)

**Comment by jenlampton** [comment]
Yep, there's a @todo in the code that needs to be cleaned up. The ideal solution would use https://github.com/backdrop/backdrop-issues/issues/1437 once it gets in. I'm going to hold off on this fix until after 1.7.3 is released and if that doesn't go in I'll do the fix another way until it's ready :)

**Comment by jenlampton** [comment]
Pushed a commit for this.
