### ISSUE TITLE
Address field example AJAX doesn't work

### ISSUE THREAD

**Issue by ItangSanjana** [backdrop-contrib/addressfield#16]
Step to reproduce:

After installing and configuring addressfield,
1. edit file `modules/addressfield/example/addressfield_example.info`.
   1. find and comment out or remove line `hidden = TRUE`.
   2. save and...
2. install the module as usual.
3. back to addressfield field configuration
   1. scroll down to `Format handlers` section.
   2. select `Example Address form (CH add-on)`.
   3. save and...
4. create a content, select country as Switzerland, fill the rest of the form, notice the AJAX doesn’t work as they do on Drupal.

**Comment by argiepiano** [comment]
I can't reproduce. This seems to be working now.
