### ISSUE TITLE
Country multiselect too short.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/addressfield#18]
This is on stock Seven theme:

![backdrop-addressfield-country-multiselect_field_too_short](https://cloud.githubusercontent.com/assets/2423362/22469621/d02164d6-e820-11e6-9f12-b375de3f4d89.png)

...notice how the second country is partially shown?

PS: or is this a core issue?

**Comment by jenlampton** [comment]
I think this is a core issue as there's nothing specially added for addressfield.
