### ISSUE TITLE
Undefined property: stdClass::$languag

### ISSUE THREAD

**Issue by bjoern-st** [backdrop-contrib/addressfield#22]
Hey @jenlampton 

I've installed your ported module and have recurring errors on the site.

Error message is:
```
Notice: Undefined property: stdClass::$language in addressfield_tokens() (Zeile 106 von l/modules/contrib/addressfield/addressfield.tokens.inc). 
```

PHP version is 5.6.33 

Cheers Bjoern

**Comment by jenlampton** [comment]
Did you try the solution in https://github.com/backdrop-contrib/addressfield/issues/20? 
Here's a direct link to a patch you can apply until the next release is out: https://github.com/jenlampton/addressfield/commit/28c053f8d8f7172c0e57eaafd5bb9c61d9ea03fe.patch
