### ISSUE TITLE
Sync address formats with upstream

### ISSUE THREAD

**Issue by bojanz** [backdrop-contrib/addressfield#25]
Addressfield 1.3 has resynced address formats with Google's dataset:

* [x] https://cgit.drupalcode.org/addressfield/commit/?id=b95e21f
* [x] https://cgit.drupalcode.org/addressfield/commit/?id=9f7061a

Also relevant:
* [x] https://cgit.drupalcode.org/addressfield/commit/?id=da0b13e
* [x] https://cgit.drupalcode.org/addressfield/commit/?id=00110ab
* [x] https://cgit.drupalcode.org/addressfield/commit/?id=461352f
* [ ] https://cgit.drupalcode.org/addressfield/commit/?id=51b6301

**Comment by jenlampton** [comment]
Thank you, I have cherry-picked all the commits from the Drupal branch.
