### ISSUE TITLE
Fixed: Not working with Feeds

### ISSUE THREAD

**Issue by sbgraphicdesign** [backdrop-contrib/addressfield#26]
When using the Feeds importer, I'm not seeing any Address fields in the mapping settings. Pretty sure it works in the D7 version. Is this likely to be an issue with the Addressfield module or the Feeds module?

**Comment by jenlampton** [comment]
> Is this likely to be an issue with the Addressfield module or the Feeds module?

It could be either one? I'm about to do some feeds importing with addresses also, I'll see if I can help pinpoint the issue.

**Comment by bobchristenson** [comment]
The address field module seems to be, at the very least, missing the addressfield.feeds.inc file.  So, it looks like the backdrop version of the module is missing some of the features of the latest D7 version.

**Comment by bobchristenson** [comment]
Wow.  If only it was always this easy:  Just drop the addressfield.feeds.inc file from the latest D7 into the module directory and...poof.  Everything works.  Hopefully that can be added to a new release!

**Comment by laryn** [comment]
Reference: https://github.com/backdrop-contrib/addressfield/commit/2fac3fe773bcc7b7587c100a0931563854b1bcbd

**Comment by jenlampton** [comment]
I guess that file is safe to add back now ;) Thanks for testing @bobchristenson!

(anyone want to make a PR?)

**Comment by jenlampton** [comment]
I've reverted the previous commit that removed the feeds integration. Thanks @laryn
