### ISSUE TITLE
"Hide postal code field" does not appear to hide zip code

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/addressfield#29]
I have added an addressfield to an entity and selected "Hide postal code field". I would like to only collect country. Unfortunately, I still see the zip code field:

<img width="825" alt="Screen Shot 2020-11-02 at 2 35 36 PM" src="https://user-images.githubusercontent.com/397895/97926732-7c7e3a80-1d18-11eb-9f5e-ae8ffb2847cc.png">

**Comment by jvillacriz** [comment]
Hello, Today (02/03/2023) "Hide postal code field" does not appear to hide zip code.   I have seen #29 and #30 but the issue occurred today.
![image](https://user-images.githubusercontent.com/68474819/216647854-5df1b073-228f-468c-b329-d4ed4b6a03b9.png)

**Comment by argiepiano** [comment]
@jvillacriz are you using the dev version of the module, or 1.3.1? This fix was merged in Nov 2020, but 1.3.1 was released earlier, in March 2020, meaning that this fix is not in the 1.3.1 version. Let me know.

We will be doing a new release very soon.

**Comment by jvillacriz** [comment]
Yes, I´m using 1.3.1 
![image](https://user-images.githubusercontent.com/68474819/216653178-c3ee7ab2-a5cd-4ab9-935b-0318d462167b.png)

**Comment by argiepiano** [comment]
You can either try downloading the dev version [here](https://github.com/backdrop-contrib/addressfield/archive/refs/heads/1.x-1.x.zip) or wait until the new release for a few days.

**Comment by argiepiano** [comment]
If you do download the dev version, be sure to revert to the latest version once it's released. If you stay with the dev version beyond that, Backdrop will not notify you of other future releases of the module.

**Comment by jvillacriz** [comment]
Thanks

**Comment by argiepiano** [comment]
@jvillacriz, I just did a new release of the module: 1.x-1.3.2.

Can you please upgrade and test again?

**Comment by jvillacriz** [comment]
Yes, it works. Thank you. 
![image](https://user-images.githubusercontent.com/68474819/216713917-ca668e79-54f2-44c7-8578-ff191b256a09.png)
