### ISSUE TITLE
Addressfield uses `entity_property_verbatim_get` and `entity_property_verbatim_set` which don't exist

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/addressfield#31]
This is happening in addressfield.module. The correct function is ~~`entity_plus_metadata_field_verbatim_get()`~~ `entity_plus_property_verbatim_get`  and ~~`entity_plus_metadata_field_verbatim_set()`~~ `entity_plus_property_verbatim_set`

ALSO, if you are going to use metadata wrappers you MUST require Entity Plus as a dependency. Otherwise this module can't be used by Rules.

**Comment by nattywebdev** [comment]
Also applies to `entity_plus_property_verbatim_get` and `entity_plus_property_verbatim_set` in addresfield.module.

**Comment by argiepiano** [comment]
Thanks, @nattywebdev. My original post for this issue had reported the wrong callback!

**Comment by argiepiano** [comment]
I'm going to close this issue, as I opened a separate one that includes a couple of other callback definitions, and makes it clearer that Rules integration doesn't work currently.
