### ISSUE TITLE
Make addressfield Rules-ready

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/addressfield#32]
Currently, `addressfield` can't be set or read by Rules.  Doing so throws errors such as `Error: Call to undefined function entity_metadata_field_verbatim_get()`

Rules uses Entity Plus to get and set fields. In order to do that, contrib modules must define callbacks for their fields and properties. Addressfield uses faulty callbacks that are not available in Entity Plus. Rather, those were available in Entity Metadata Wrapper, an old module that has been deprecated.

The faulty callbacks are:

- `entity_property_verbatim_get`
- `entity_property_verbatim_set`
- `entity_metadata_field_verbatim_get`
- `entity_metadata_field_verbatim_set`

All that's needed is to insert `_plus_` after `entity`
 
This is related to #31, but that issue only focused on `entity_property_verbatim_set` and `get`

**Comment by argiepiano** [comment]
PR #33 provided.

**Comment by argiepiano** [comment]
One more benefit of making this fix is that you can use Entity Tokens to "drill" into address fields (to get for example, the postal code). Without this fix, you get a fatal error, since the property callback doesn't work. 

Any maintainer interested in reviewing, please? @jenlampton?

**Comment by nattywebdev** [comment]
I can confirm that patch derived from #33 fixed the issue described above. I'm using BackdropCMS v1.23.1. 
Thank you @argiepiano

**Comment by argiepiano** [comment]
Thanks for testing @nattywebdev!
