### ISSUE TITLE
Fix Address Field tokens

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/addressfield#37]
Currently, most (all?) tokens provided by Address Field do not work.

To reproduce
---
One way to reproduce:
1. Add an address field to the user entity at `admin/config/people/manage`. Call it "Address" (machine name: `field_address`)
2. Edit the admin user to add an address, include a postal code
3. Enable Token Filter. Be sure to enable "Replace tokens" for Raw HTML format at `admin/config/content/formats/full_html`
4. Create a page. Be sure to select "Raw HTML" in "Formatting options" for the Body field
5. In the body field add `[current-user:field_address:postal-code]` to show the zip code of the current user
6. View the page.

Actual behavior 
---
The token is not fulfilled

Expected behavior
---
The zip code of the current user should be shown. This works fine in D7.

Additional information
---
These tokens don't work because of how the module `Token` was incorporated into core. In D7, `Token` had a special token type called `entity` that was caught by Address Field in `addressfield_tokens()` to do a `token_generate()` with type `address-field`.   But the token utilities now in Backdrop core do not use the `entity` token type anymore.

The solution is pretty straightforward, though. PR forecoming.

**Comment by argiepiano** [comment]
PR submitted: #38 

In addition to fixing the token generating code, this PR gets rid of unnecessary (and faulty) code in `addressfield_get_address_fields()`. The removed code was added in #1 because the function `field_info_field_map()` did not exist in Backdrop's core at the time. Then, that code was modified in another issue, BUT the modifications weren't tested thoroughly (`field_info_instances($entity_type);` returns an array keyed by `bundle`, yet the faulty code assumed the keys were field names).  

In any case, the old faulty code generates a notice, now that tokens are working.

**Comment by argiepiano** [comment]
I just pushed one additional small change to `addressfield_get_address_fields()` (taken actually from the D7 version), which fixes another issue with tokens. 

Before, if you added an `addressfield` field to any entity (e.g. `user`), and then visited a page with a token browser (e.g. the content type page), the subtokens provided by `addressfield` did not show up under the entity and the field.  With this small change I just pushed those tokens now show up.

**Comment by nattywebdev** [comment]
I can confirm that patches arising from #37 and #38 fixed the issues described above. I'm using BackdropCMS v1.23.1. I had also applied the patch derived from #32. Thank you @argiepiano

**Comment by argiepiano** [comment]
Thanks for testing, @nattywebdev! 

Merging...

**Comment by argiepiano** [comment]
Oops. I can't merge. I don't have the required access level. @jenlampton, can you help?
